/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jnitest2_MainActivity */

#ifndef _Included_com_example_jnitest2_MainActivity
#define _Included_com_example_jnitest2_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jnitest2_MainActivity
 * Method:    getSum
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jnitest2_MainActivity_getSum
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
